import type {
  PreparedOrderDraft,
} from "./types";

export type OrderStatus =
  | "pending"
  | "paid";

export interface PendingOrderRecord
  extends PreparedOrderDraft {
  /*
   * orderId must be generated by the real
   * server-side persistence implementation.
   * This contract does not generate IDs.
   */
  orderId: string;

  status:
    OrderStatus;

  authority:
    string | null;

  refId:
    string | null;

  createdAt:
    string;

  paidAt:
    string | null;
}

export interface AttachAuthorityInput {
  orderId: string;
  authority: string;
}

export interface MarkOrderPaidInput {
  orderId: string;
  authority: string;

  refId:
    string | null;

  paidAt:
    string;
}

export interface OrderRepository {
  createPending(
    order:
      PreparedOrderDraft,
  ): Promise<PendingOrderRecord>;

  findById(
    orderId: string,
  ): Promise<PendingOrderRecord | null>;

  findByAuthority(
    authority: string,
  ): Promise<PendingOrderRecord | null>;

  attachAuthority(
    input:
      AttachAuthorityInput,
  ): Promise<PendingOrderRecord>;

  markPaid(
    input:
      MarkOrderPaidInput,
  ): Promise<PendingOrderRecord>;
}
